# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal

index:
    pattern: /
    defaults:
        _controller: AppBundle:Index:index

# Original config
#
# TODO: Can this be removed?
#
# oauth_google:
#     pattern: /login/google-check
#
# oauth_github:
#     pattern: /login/github-check
#
# hwi_oauth_login:
#     prefix: /login
#     resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
# 
# hwi_oauth_connect:
#     prefix: /login/connect
#     resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"

hwi_oauth_redirect:
    prefix:   /connect
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"

fos_comment_api:
    type: rest
    resource: "@FOSCommentBundle/Resources/config/routing.yml"
    prefix: /comment

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
